config/routes.rb
Rails.application.routes.draw do
  root "blogs#home"
  resources :blogs

  scope :auth do
    get "sign-in", to: "auth#sign_in", as: :sign_in
    post "sign-in", to: "auth#login", as: :login
    get "sign-up", to: "auth#sign_up", as: :sign_up
    post "sign-up", to: "auth#create_user", as: :create_user
    post "logout", to: "auth#logout", as: :logout
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :body, presence: true
    validates :title, uniqueness: true

    belongs_to :user
    has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, :password_digest, presence: true
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "Email is not valid" }, presence: true, uniqueness: true

    has_secure_password
    has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user

    def authenticate_user
        @user = User.find(session[:user]) if session[:user]
        @user_signed_in = @user.present?
        @current_user = @user
    end

    def requires_login
        redirect_to sign_in_path, notice: "You need sign in" unless @user_signed_in
    end

    def requires_guest
        redirect_to root_path, notice: "You are already signed in" if @user_signed_in
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    before_action :requires_guest, except: [ :logout ]
    before_action :requires_login, only: [ :logout ]

    def sign_in
    end
    
    def sign_up
    end

    
    def login
        credentials = params[:credentials]
        user = User.find_by(email: credentials[:email])

         respond_to do |format|
            if user.present?
                if user.authenticate(credentials[:password])
                    session[:user] = user.id
                    format.html { redirect_to root_path, notice: "Successfully logged in 🎉"}
                else
                    format.html {redirect_to sign_in_path, notice: "Password is incorrect"}
                end
            elsif !user.present?
                format.html {redirect_to sign_in_path, notice: "user with email does not exists"}
            end
        end
    end

    def create_user
        user_params = params[:user].permit!

        respond_to do |format|
            if User.create(user_params)
                format.html { redirect_to sign_in_path, notice: "User successfully created" }
            else
                user = User.create(user_params)
                if user.errors&.full_messages.present? 
                    format.html {redirect_to sign_up_path, notice: "#{user.errors.full_messages[0]}"}
                end
            end
        end
    end

    def logout
        session[:user] = nil
        redirect_to sign_in_path, notice: "Successfully logged out"
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :requires_login, except: %i[ home show]
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def home
    @blogs = Blog.all
  end

  # GET /blogs for specific user
  def index
    @blogs = @user.blogs
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = @user.blogs.create(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy!

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>" class="px-6 py-8 border-b border-[#4a4a4a]" >
  <p class="pb-4 font-bold">
    <%= blog.title.truncate(75) %>
  </p>

  <p class="text-[#939393] text-justify text-sm">
    <%= blog.body.to_plain_text.truncate_words(50) %>
  </p>


  <span class="text-xs px-2.5 py-2 rounded-full bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mr-2 hover:bg-[#1e1e1e]"><%= link_to "read more", blog %></span>

 

  <% if blog.user == @current_user %>
  <span class="bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mt-4 text-xs font-medium inline-flex items-center px-2.5 py-2 rounded-full mr-2  hover:bg-[#1e1e1e]">
  <svg aria-hidden="true" class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
  You published this article <%= time_ago_in_words(blog.created_at) %> ago
</span>
<% else %>
  <span class="bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mt-4 text-xs font-medium inline-flex items-center px-2.5 py-2 rounded-full mr-2 dark:bg-gray-700 dark:text-gray-300 hover:bg-[#1e1e1e]">
    <svg aria-hidden="true" class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
    <%= blog.user.first_name %> published this article <%= time_ago_in_words(blog.created_at) %> ago
  </span>
<% end %>




</div>

app/views/blogs/_form.html.erb
<div class="my-8">
  <%= form_with(model: blog) do |form| %>
    <% if blog.errors.any? %>
      <div style="color: red">
        <ul>
          <% blog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "bg-[#191919] border-[#4a4a4a] my-2 w-full" %>
    </div>
  
    <div class="my-4">
      <%= form.label :body, style: "display: block", class:"pb-3"  %>
      <%= form.rich_text_area :body, class: "block my-2 w-full" %>
    </div>
  
    <div>
        <span class="text-xs px-4 py-2 rounded-full bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mr-2 hover:border-green-900 hover:bg-green-700"><%= form.submit %></span>
    </div>
  <% end %>
</section>

app/views/blogs/edit.html.erb
<div class="my-8">
     <div class="flex justify-between">
       <div class="flex">
         <div class="inline-block mt-1 mr-4">
              <%= link_to root_path do %> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#4a4a4a" class="w-6 h-6 hover:stroke-[#7e7e7e]"> <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75"/></svg>
              <% end %>
              </div>
           <div>
             <h1 class="text-[#eaeaea] text-xl font-bold py-1">Edit this Post</h1>
           </div>
       </div>

         <div class="flex space-x-4 items-center">
      
           
           <span class="text-xs px-2.5 py-2 rounded-full bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mr-2 hover:bg-purple-700"><%= link_to "view this post", @blog %></span>
         </div>
     </div>
  
  <%= render "form", blog: @blog %>
  

</div>

app/views/blogs/home.html.erb
<section class="mt-20">
    <%# render navbar partial from shared %>
    <%= render "shared/navbar" %>

    <%# render notice %>
    <% if notice.present? %>
    <p class="pt-2 pl-6 text-sm text-green-700 inline-block" id="notice">
        <%= notice %>
    </p>
    <% end %>

    <div id="blogs" >
        <% @blogs.each do |blog| %>
            <%= render blog %>
        <% end %>
    </div>
</section>

app/views/blogs/index.html.erb
<section class="mt-20">

<div class="fixed top-0 left-50% w-3/5 mx-auto bg-[#111111] border-b border-[#4a4a4a] px-2 sm:px-4 py-3 dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

    <div class="flex space-x-6">
      <%# return Arrow %>
      <%= link_to root_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#4a4a4a" class="w-6 h-6 hover:stroke-[#7e7e7e] ">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75" />
          </svg>
      <% end %>

        <p class="text-[#eaeaea] font-medium text-md">Hello, <%= @user.first_name %></p>
    </div>


  <div class="flex md:order-2 space-x-2">
      <button><%= link_to "Sign Out", logout_path, method: :post, data: { turbo_method: :post }, class: "text-[#eaeaea] bg-[#111] border border-[#4a4a4a] hover:bg-[#1e1e1e] font-medium rounded-full text-sm px-5 py-2.5 text-center mr-3 md:mr-0" %></button>
      
      <button type="button" class="text-[#eaeaea] bg-[#111] border border-[#4a4a4a] hover:bg-[#1e1e1e] font-medium rounded-full text-sm px-5 py-1.5 text-center mr-3 md:mr-0">
          <%= link_to new_blog_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <% end %>
      </button>
  </div>
  </div>
</div>


<%# render notice %>
<% if notice.present? %>
  <p class="py-2 pl-6 text-sm text-green-700 inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

  <div id="blogs" class="">
    <% @blogs.each do |blog| %>
        <%= render blog %>
    <% end %>
  </div>
</section>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="mt-12 mb-20">

  <% if notice.present? %>
  <p class="py-4 bg-[#111] border border-green-700 text-xs mb-5 text-green-700 rounded-full px-6 inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

   <div class="flex mb-2">
     <div class="inline-block mt-1 mr-4">
          <%= link_to root_path do %> <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#4a4a4a" class="w-6 h-6 hover:stroke-[#7e7e7e]"> <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75"/></svg>
          <% end %>
          </div>
       <div class="text-2xl font-bold"><%= @blog.title %></div>
   </div>

  <% if @blog.user == @current_user %>
  <span class="bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mt-4 text-xs font-medium inline-flex items-center px-2.5 py-2 rounded-full mr-2  hover:bg-[#1e1e1e]">
  <svg aria-hidden="true" class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
  You published this article <%= time_ago_in_words(@blog.created_at) %> ago
</span>

  <span class="text-xs px-2.5 py-2 rounded-full bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mr-2 hover:border-green-900 hover:bg-green-700"><%= link_to "Edit post", edit_blog_path(@blog) %></span>

  <span class="text-xs px-2.5 py-2 rounded-full bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mr-2 hover:border-red-900 hover:bg-red-800"><%= link_to "Delete Post", @blog, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this Blog Post?" } %></span>
<% else %>
  <span class="bg-[#111111] border border-[#4a4a4a] text-[#eaeaea] mt-4 text-xs font-medium inline-flex items-center px-2.5 py-2 rounded-full mr-2 dark:bg-gray-700 dark:text-gray-300 hover:bg-[#1e1e1e]">
    <svg aria-hidden="true" class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd"></path></svg>
    <%= @blog.user.first_name %> published this article <%= time_ago_in_words(@blog.created_at) %> ago
  </span>
<% end %>
  <div class="text-[#939393] text-[0.9rem] text-justify my-8"><%= @blog.body %></div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App - AltSchool Exams</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-[#111111] text-[#eaeaea] font-MonoLisa">
    <main class="container w-3/5 mx-auto">
    <%= yield  %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="fixed top-0 left-50% w-3/5 mx-auto bg-[#111111] border-b border-[#4a4a4a] px-2 sm:px-4 py-3 dark:bg-gray-900">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

  <%# linkto root path %>
    <%= link_to "Blogger", root_path, class: "text-[#eaeaea] hover:text-[#cdcdcd] font-bold text-xl" %>

  <div class="flex md:order-2 space-x-2">
  
    <% if @user_signed_in %>
      <button>
        <%= link_to "View your posts", blogs_path, class: "text-[#eaeaea] bg-[#111] border border-[#4a4a4a] hover:bg-[#1e1e1e] font-medium rounded-full text-sm px-5 py-2.5 text-center mr-3 md:mr-0" %>
      </button>
      
      <button type="button" class="text-[#eaeaea] bg-[#111] border border-[#4a4a4a] hover:bg-[#1e1e1e] font-medium rounded-full text-sm px-5 py-1.5 text-center mr-3 md:mr-0">
          <%= link_to new_blog_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"> <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" /></svg>
          <% end %>
      </button>
    <% else %>
      <button><%= link_to "Sign In", sign_in_path, class: "text-[#eaeaea] hover:text-[#cdcdcd] font-medium rounded-full text-sm px-5 text-center mr-3 md:mr-0" %></button>

      <button><%= link_to "Create an Account", sign_up_path, class: "text-[#eaeaea] bg-[#111] border border-[#4a4a4a] hover:bg-[#1e1e1e] font-medium rounded-full text-sm px-5 py-2.5 text-center mr-3 md:mr-0" %></button>
    <% end %>
  </div>
 
  </div>
</nav>